### ISSUE TITLE
Exception handling using otto bus

### ISSUE THREAD

**Issue by markzyu** [TakefiveInteractive/Ledger-Android#5]
Create an Event tenplate to wrap any Exception

**Comment by markzyu** [comment]
Or just send a SnackBar object to UI thread for show()

**Comment by markzyu** [comment]
@lafickens either way I believe there is no need to create a "Maybe" type (`LoginEvent`) because we could just distinguish success and failure type and let otto bus do the binding.

**Comment by mar29th** [comment]
I understand. Wrapping exceptions is a good idea; cross-thread calls are not exactly ideal.

**Comment by markzyu** [comment]
eventually we use actionchain with errorholder...
